/* AUTO-GENERATED by tools/compile-demos.js — attract-mode solution recordings.
 * Each entry: {frame, lemmingIndex, skill}. Verified solvable by tools/verify.js. */
(function (G) {
  const BT = G.BT;
  BT.DEMOS = {
    "T": [
      {"frame":785,"lemmingIndex":0,"skill":"basher"}
    ],
    "1-1": [
      {"frame":692,"lemmingIndex":0,"skill":"builder"}
    ],
    "1-2": [
      {"frame":882,"lemmingIndex":0,"skill":"digger"}
    ],
    "1-3": [
      {"frame":832,"lemmingIndex":0,"skill":"miner"}
    ],
    "2-1": [
      {"frame":995,"lemmingIndex":0,"skill":"builder"},
      {"frame":995,"lemmingIndex":1,"skill":"blocker"},
      {"frame":1333,"lemmingIndex":0,"skill":"builder"},
      {"frame":1498,"lemmingIndex":1,"skill":"bomber"}
    ],
    "2-2": [
      {"frame":897,"lemmingIndex":0,"skill":"miner"},
      {"frame":1878,"lemmingIndex":0,"skill":"basher"}
    ],
    "2-3": [
      {"frame":665,"lemmingIndex":0,"skill":"blocker"},
      {"frame":665,"lemmingIndex":0,"skill":"bomber"}
    ],
    "3-1": [
      {"frame":1625,"lemmingIndex":0,"skill":"builder"},
      {"frame":1625,"lemmingIndex":1,"skill":"blocker"},
      {"frame":2025,"lemmingIndex":1,"skill":"bomber"}
    ],
    "3-2": [
      {"frame":388,"lemmingIndex":0,"skill":"miner"}
    ],
    "3-3": [
      {"frame":675,"lemmingIndex":0,"skill":"builder"},
      {"frame":1967,"lemmingIndex":0,"skill":"builder"},
      {"frame":1967,"lemmingIndex":4,"skill":"blocker"},
      {"frame":2367,"lemmingIndex":4,"skill":"bomber"},
      {"frame":4959,"lemmingIndex":0,"skill":"miner"}
    ],
    "4-1": [
      {"frame":689,"lemmingIndex":0,"skill":"basher"},
      {"frame":1324,"lemmingIndex":0,"skill":"digger"}
    ],
    "4-2": [
      {"frame":858,"lemmingIndex":0,"skill":"builder"},
      {"frame":858,"lemmingIndex":1,"skill":"blocker"},
      {"frame":1197,"lemmingIndex":0,"skill":"builder"},
      {"frame":1391,"lemmingIndex":1,"skill":"bomber"},
      {"frame":1790,"lemmingIndex":0,"skill":"digger"}
    ],
    "4-3": [
      {"frame":177,"lemmingIndex":0,"skill":"climber"},
      {"frame":276,"lemmingIndex":1,"skill":"climber"},
      {"frame":1440,"lemmingIndex":0,"skill":"blocker"},
      {"frame":1585,"lemmingIndex":1,"skill":"basher"},
      {"frame":1797,"lemmingIndex":0,"skill":"bomber"}
    ],
    "5-1": [
      {"frame":135,"lemmingIndex":0,"skill":"floater"},
      {"frame":990,"lemmingIndex":0,"skill":"builder"},
      {"frame":994,"lemmingIndex":1,"skill":"blocker"},
      {"frame":1350,"lemmingIndex":1,"skill":"bomber"},
      {"frame":1350,"lemmingIndex":2,"skill":"floater"},
      {"frame":1350,"lemmingIndex":3,"skill":"floater"},
      {"frame":1350,"lemmingIndex":4,"skill":"floater"},
      {"frame":1350,"lemmingIndex":5,"skill":"floater"},
      {"frame":1350,"lemmingIndex":6,"skill":"floater"},
      {"frame":1350,"lemmingIndex":7,"skill":"floater"},
      {"frame":1350,"lemmingIndex":8,"skill":"floater"},
      {"frame":1350,"lemmingIndex":9,"skill":"floater"},
      {"frame":1373,"lemmingIndex":10,"skill":"floater"},
      {"frame":1497,"lemmingIndex":11,"skill":"floater"},
      {"frame":1620,"lemmingIndex":12,"skill":"floater"}
    ],
    "5-2": [
      {"frame":822,"lemmingIndex":0,"skill":"basher"},
      {"frame":1692,"lemmingIndex":0,"skill":"miner"},
      {"frame":2584,"lemmingIndex":0,"skill":"basher"},
      {"frame":3192,"lemmingIndex":0,"skill":"builder"}
    ],
    "5-3": [
      {"frame":555,"lemmingIndex":1,"skill":"builder"},
      {"frame":578,"lemmingIndex":3,"skill":"blocker"},
      {"frame":915,"lemmingIndex":3,"skill":"bomber"},
      {"frame":3795,"lemmingIndex":1,"skill":"basher"},
      {"frame":4403,"lemmingIndex":1,"skill":"digger"},
      {"frame":5412,"lemmingIndex":1,"skill":"basher"}
    ],
  };
})(typeof window !== 'undefined' ? window : globalThis);
