/* ==========================================================================
 * tools/compile-demos.js
 * Resolves each level's human-authored solution script (conditional
 * triggers such as "lemming 0 becomes a builder when it reaches x=236")
 * into an exact frame-stamped recording [{frame, lemmingIndex, skill}],
 * checks that the recording actually solves the level, and writes
 * js/demos.js. Usage:  node tools/compile-demos.js [levelIndex] [--png]
 * ========================================================================== */
'use strict';
const path = require('path');
const fs = require('fs');
const root = path.join(__dirname, '..', 'js');
for (const f of ['core', 'terrain', 'sim', 'levels']) require(path.join(root, f + '.js'));
const BT = globalThis.BT;
const { snapshot } = require('./png');

const args = process.argv.slice(2);
const png = args.includes('--png');
const only = args.find((a) => !a.startsWith('--'));
const demoFile = path.join(root, 'demos.js');
let existing = {};
try { require(demoFile); existing = globalThis.BT.DEMOS || {}; } catch (e) { existing = {}; }

const hue = (i) => {
  const h = (i * 0.137) % 1, f = h * 6, k = Math.floor(f), t = f - k;
  const c = [[1, t, 0], [1 - t, 1, 0], [0, 1, t], [0, 1 - t, 1], [t, 0, 1], [1, 0, 1 - t]][k % 6];
  return c.map((v) => Math.round(80 + v * 175));
};

function lemOk(sim, s, L) {
  const stName = s.st || (s.x !== undefined ? 'WALK' : null);
  if (stName && stName !== 'ANY' && L.st !== BT.ST[stName]) return false;
  if (s.x !== undefined && L.x !== s.x) return false;
  if (s.xmin !== undefined && L.x < s.xmin) return false;
  if (s.xmax !== undefined && L.x > s.xmax) return false;
  if (s.dir !== undefined && L.dir !== s.dir) return false;
  if (s.y !== undefined && L.y < s.y) return false;
  if (s.ymax !== undefined && L.y > s.ymax) return false;
  if (s.notTag && s.notTag.some((t) => tags[t] === L.id)) return false;
  return true;
}
let tags = {};
const resolve = (v) => (typeof v === 'string' && v[0] === '$' ? tags[v.slice(1)] : v);
/* Returns the lemming index to assign (or -1 for global commands), or null if not ready. */
function ready(sim, s, lastFire) {
  if (s.frame !== undefined && sim.frame < s.frame) return null;
  if (s.after !== undefined && sim.frame < lastFire + s.after) return null;
  if (s.pick) {
    for (const L of sim.lems) if (L.st < BT.ST.DEAD && lemOk(sim, s, L) && sim.canAssign(L, s.skill)) return L.id;
    return null;
  }
  if (s.lem === undefined) return -1;
  const target = resolve(s.lem);
  const cond = s.on !== undefined ? resolve(s.on) : target;
  const L = sim.lems[cond];
  if (!L || target === undefined || !sim.lems[target]) return null;
  if (!lemOk(sim, s, L)) return null;
  return target;
}

const out = Object.assign({}, existing);
let allOk = true;
BT.LEVELS.forEach((def, li) => {
  if (only !== undefined && String(li) !== only) return;
  tags = {};
  const sim = new BT.Sim(def);
  const init = sim.terrain.clone();
  const script = def.solution || [];
  const rec = [];
  const trails = [];
  let k = 0, lastFire = 0;
  while (!sim.ended) {
    while (k < script.length) {
      const s = script[k];
      const idx = ready(sim, s, lastFire);
      if (idx === null) break;
      const cmd = { frame: sim.frame, lemmingIndex: idx, skill: s.skill };
      if (s.value !== undefined) cmd.value = s.value;
      const ok = BT.applyCommand(sim, cmd);
      if (!ok) break;
      if (s.tag) tags[s.tag] = idx;
      rec.push(cmd);
      lastFire = sim.frame;
      k++;
    }
    const t0 = sim.tick;
    sim.step();
    if (png && sim.tick !== t0) for (const L of sim.lems) if (L.st < BT.ST.DEAD) trails.push([L.x, L.y - 1, hue(L.id)]);
  }
  const ok = sim.saved >= sim.need && k === script.length;
  if (!ok) allOk = false;
  const skillsUsed = {};
  for (const r of rec) if (BT.SKILLS.includes(r.skill)) skillsUsed[r.skill] = (skillsUsed[r.skill] || 0) + 1;
  console.log(
    `${String(li).padStart(2)} ${def.id.padEnd(4)} ${def.name.padEnd(26)} saved ${String(sim.saved).padStart(2)}/${def.count} need ${def.save} ` +
    `${ok ? 'OK  ' : 'FAIL'} end=${sim.endReason} frame=${sim.frame}/${sim.timeLimit} cmds ${k}/${script.length} ${JSON.stringify(skillsUsed)}`
  );
  if (k < script.length) console.log('    stuck at trigger', JSON.stringify(script[k]));
  out[def.id] = rec;
  if (png) {
    const dir = path.join(__dirname, 'out');
    fs.mkdirSync(dir, { recursive: true });
    snapshot(BT, sim, path.join(dir, `level_${li}.png`), trails, init);
    const s0 = new BT.Sim(def);
    snapshot(BT, s0, path.join(dir, `level_${li}_start.png`));
  }
});

let js = '/* AUTO-GENERATED by tools/compile-demos.js — attract-mode solution recordings.\n' +
  ' * Each entry: {frame, lemmingIndex, skill}. Verified solvable by tools/verify.js. */\n' +
  '(function (G) {\n  const BT = G.BT;\n  BT.DEMOS = {\n';
for (const def of BT.LEVELS) {
  const r = out[def.id] || [];
  js += `    ${JSON.stringify(def.id)}: [\n` + r.map((c) => '      ' + JSON.stringify(c)).join(',\n') + (r.length ? '\n' : '') + '    ],\n';
}
js += '  };\n})(typeof window !== \'undefined\' ? window : globalThis);\n';
fs.writeFileSync(demoFile, js);
console.log(allOk ? 'ALL OK' : 'SOME LEVELS FAILED');
process.exitCode = allOk ? 0 : 1;
